import { useState,useEffect } from "react";
import Head from "next/head";

export default function ProfileUpdate () {
    const [screenHeight,setScreenHeight] = useState(0);

    useEffect(() => {
        setScreenHeight(window.innerHeight - 60);
    },[]);

    return (
        <>
        <Head>
            <title>Talent Profile Update | Real Fast</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/realfast_logo.png" />
        </Head>
        <main className={styles.container} style={{minHeight:`${screenHeight}px`}}>
            <div className={styles.wrapper}>
                <h2 className={styles.title}>Update your profile</h2>

                <form>
                    <div className={styles.inputBlockRow}>
                        <div className={styles.inputBlock}>
                            <label className={styles.label}>first name</label>
                            <input 
                            type="text" 
                            placeholder="first and middle name"
                            className={styles.inputField}/>
                        </div>
                        <div className={styles.inputBlock}>
                            <label className={styles.label}>last name</label>
                            <input 
                            type="text" 
                            placeholder="surname"
                            className={styles.inputField}/>
                        </div>
                    </div>

                    <div className={styles.inputBlockMain}>
                        <label className={styles.label}>Phone number</label>
                        <input 
                        type="tel" 
                        placeholder="phone number"
                        className={styles.inputField}/>
                    </div>

                    <div className={styles.inputBlockMain}>
                        <label className={styles.label}>Address</label>
                        <input 
                        type="text" 
                        placeholder="contact address"
                        className={styles.inputField}/>
                    </div>

                    <div className={styles.inputBlockRow}>
                        <div className={styles.inputBlock}>
                            <label className={styles.label}>Date of birth</label>
                            <input 
                            type="date" 
                            className={styles.inputField}/>
                        </div>
                        <div className={styles.inputBlock}>
                            <label className={styles.label}>Gender</label>
                            <select
                            className={styles.inputField}>
                                <option value='Not specified'>not specified</option>
                                <option value='Female'>female</option>
                                <option value='Male'>male</option>
                            </select>
                        </div>
                    </div>

                    <button type="submit" className={styles.submitBtn}>Update Profile</button>
                </form>
            </div>
        </main>
        </>
    )
}

const styles = {
    container:'w-full flex flex-col justify-center items-center px-16',
    wrapper:'w-full md:w-[720px] py-8',
    title:'text-xl text-center mb-4',
    inputBlockRow:'w-full flex flex-col md:flex-row md:gap-3 md:mb-4',
    inputBlock:'w-full mb-4',
    inputBlockMain:'w-full mb-4',
    label:'text-gray-500 mb-2',
    inputField:'w-full block border border-gray-200 py-5 px-4 rounded-full',
    submitBtn:'w-full bg-indigo-800 py-5 px-4 rounded-full text-lg text-white'
}